version: '3.9'

services:
  db:
    image: postgres:16
    container_name: vrem_postgres
    restart: always
    environment:
      POSTGRES_DB: vrem
      POSTGRES_USER: vrem_user
      POSTGRES_PASSWORD: vrem_pass
    ports:
      - '5432:5432'
    volumes:
      - vrem_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vrem_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  vrem_pgdata:
